<center> <h1>Universidad Nacional de San Agustín de Arequipa</h1> </center> 
<center> <h1>Escuela Profesional de Ingeniería de Telecomunicaciones</h1> </center> 

<center> <h1> </h1> </center> 

<center><img src="https://user-images.githubusercontent.com/19308295/115939517-f1c6fe80-a463-11eb-989c-812ab4942586.png" width="380" height="4200"></center>

<center> <h2>Ingeniero Renzo Bolivar - Docente DAIE</h2> </center> 

<center> <h1>Curso : Computación 2</h1> </center>

# <center>Grupo A-7
# <center>Viza Zapana Bryan Fernando

![linea 1](https://user-images.githubusercontent.com/19308295/115926252-2b8a0c00-a448-11eb-9d9c-b43beaf0ff68.png)

<center> <h1>NUMPY</h1> </center> 

![linea 1](https://user-images.githubusercontent.com/19308295/115926252-2b8a0c00-a448-11eb-9d9c-b43beaf0ff68.png)

# Descripción:

En este notebook se explicarán _NumPy_ la librería de cálculo numérico uno de los paquetes centrales para la computación numérica en Python.

# Objetivos:


 1. Familiarizarce con las matrices en NumPy
 2. Creación de matrices en Numpy
 3. Comprobar la facilidad de uso en NumPy

# Contenido:

[1. Numpy: Librería de cálculo numérico](#1.-Numpy:-Librería-de-cálculo-numérico)<br>
[2. Numpy: Funciones básicas](#2.-Numpy:-Funciones-básicas)<br>
[3. Inspeccionar matrices de NumPy](#3.-Inspeccionar-matrices-de-NumPy)<br>
[4. Operaciones Matemáticas entre matrices de NumPy](#4.-Operaciones-Matemáticas-entre-matrices-de-NumPy)<br>

[EJEMPLOS](#EJEMPLOS)<br>
[EJERCICIOS](#EJERCICIOS)<br>
[BIBLIOGRAFÍA](#BIBLIOGRAFÍA)<br>

![linea 1](https://user-images.githubusercontent.com/19308295/115926252-2b8a0c00-a448-11eb-9d9c-b43beaf0ff68.png)

## <font color=#33A5FF>****1. Numpy: Librería de cálculo numérico****<tfont>

<img src="https://user-images.githubusercontent.com/19308295/115939595-32bf1300-a464-11eb-8c50-6f05dce9a805.png"
    style="width:300px; float: right; margin: 0 40px 40px 40px;"></img>

NumPy (Numerical Python) es uno de los paquetes centrales para la computación numérica en Python. Pandas, Matplotlib, Statmodels y muchas otras librerías científicas dependen de NumPy.

Las principales contribuciones de NumPy son:

* Computación numérica eficiente con código "C"
* Recopilaciones eficientes con operaciones vectoriales
* Un Aplicativo (API) de álgebra lineal integrada y natural
* Un Aplicativo (API) en C para conectar NumPy con librerías escritas en C, C++ o FORTRAN.

Desarrollemos la eficiencia. En Python, **todo es un objeto**, lo que significa que incluso los simples __enteros (int)__ son también objetos, con toda la maquinaria necesaria para hacer que el objeto funcione. Los llamamos "Boxed Ints". En cambio, `NumPy` utiliza tipos numéricos primitivos (floats, ints) que hacen que el almacenamiento y el cálculo sean eficientes.


![Python Boxed Ints vs C and Numpy](https://user-images.githubusercontent.com/19308295/115942212-b2ea7600-a46e-11eb-86ed-d7cdc9dffbe0.png)


<img src="https://user-images.githubusercontent.com/19308295/115942590-98b19780-a470-11eb-84b0-a6390e928eb3.png"
    style="width:700px"></img>


<div class="well">

<strong>Utilización de NumPy:</strong>
    
* En Matemáticas (Reemplaza al MATLAB)
* Genera Gráficos a partir de Matrices Numpy 
* Backend (Pandas, Connect 4 Games, Fotografía Digital)
* Machine Learning.
    
</div>

<div class="well">

<strong>NumPy Array o el arreglo de matrices de NumPy</strong> es un potente objeto de matriz N-dimensional que tiene forma de filas y columnas, en la que tenemos varios elementos que están almacenados en sus respectivas ubicaciones de memoria. 
    
En la siguiente imagen, es una <strong>matriz bidimensiona</strong>l porque tiene filas y columnas, como puedes ver tiene cuatro filas y tres columnas, por lo que se convierte en una matriz bidimensional. En el caso de que solo tuviera una fila entonces habría sido una matriz unidimensional.
    
</div>

![Practica_04](https://user-images.githubusercontent.com/19308295/115941133-c8a96c80-a469-11eb-8e21-117c1e84bf69.png)

![linea 2](https://user-images.githubusercontent.com/19308295/115926262-2fb62980-a448-11eb-8189-c2f10e499944.png)

## <font color=#33A5FF>****EJERCICIOS****<tfont>

<center> <h2>Ejercicio 01</h2> </center> 

* Crear un array 7x8 lleno de ceros de tipo entero.
* Crear un array 7x8 lleno de ceros salvo la primera fila que serán todo unos.
* Crear un array 7x8 lleno de ceros salvo la última fila que será el rango entre 5 y 8.

In [2]:
import numpy as np
# 01: Crear un array 7x8 lleno de ceros de tipo entero
array_ceros = np.zeros((7, 8), dtype=int)
print("Array 7x8 lleno de ceros de tipo entero:")
print(array_ceros)

Array 7x8 lleno de ceros de tipo entero:
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


In [3]:
# 02: Crear un array 7x8 lleno de ceros salvo la primera fila que serán todo unos
array_ceros_primera_fila_unos = np.zeros((7, 8), dtype=int)
array_ceros_primera_fila_unos[0, :] = 1
print("\nArray 7x8 lleno de ceros salvo la primera fila que serán todo unos:")
print(array_ceros_primera_fila_unos)


Array 7x8 lleno de ceros salvo la primera fila que serán todo unos:
[[1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


In [4]:
# 03: Crear un array 7x8 lleno de ceros salvo la última fila que será el rango entre 5 y 12
array_ceros_ultima_fila_rango = np.zeros((7, 8), dtype=int)
array_ceros_ultima_fila_rango[-1, :] = np.arange(5, 13)
print("\nArray 7x8 lleno de ceros salvo la última fila que será el rango entre 5 y 12:")
print(array_ceros_ultima_fila_rango)


Array 7x8 lleno de ceros salvo la última fila que será el rango entre 5 y 12:
[[ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 5  6  7  8  9 10 11 12]]


![linea 2](https://user-images.githubusercontent.com/19308295/115926262-2fb62980-a448-11eb-8189-c2f10e499944.png)

## <font color=#33A5FF>****BIBLIOGRAFÍA****<tfont>

[1] Documentación de NumPy http://docs.scipy.org/doc/numpy

[2] Travis Oliphant, "Guide to NumPy" http://csc.ucdavis.edu/~chaos/courses/nlp/Software/NumPyBook.pdf

[3] SciPy Lecture Notes http://scipy-lectures.github.io

[4] Nicolas Rougier, "100 NumPy exercises" http://www.loria.fr/~rougier/teaching/numpy.100/index.html

![linea 1](https://user-images.githubusercontent.com/19308295/115926252-2b8a0c00-a448-11eb-9d9c-b43beaf0ff68.png)